# Generated by Django 5.1.1 on 2026-05-06 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_result_user_profil_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trieda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Triedy',
            },
        ),
        migrations.AddField(
            model_name='profil',
            name='trieda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studenti', to='quiz.trieda'),
        ),
        migrations.AddField(
            model_name='test',
            name='assigned_classes',
            field=models.ManyToManyField(blank=True, related_name='tests', to='quiz.trieda'),
        ),
    ]
